/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donation = IDL.Record({ 'timestamp' : Time, 'amount' : IDL.Nat });
export const CampaignStats = IDL.Record({
  'percentageComplete' : IDL.Float64,
  'targetMeals' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'mealsSponsored' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getCampaignStats' : IDL.Func([], [CampaignStats], ['query']),
  'getMealsSponsored' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalAmountRaised' : IDL.Func([], [IDL.Nat], ['query']),
  'makeDonation' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donation = IDL.Record({ 'timestamp' : Time, 'amount' : IDL.Nat });
  const CampaignStats = IDL.Record({
    'percentageComplete' : IDL.Float64,
    'targetMeals' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'mealsSponsored' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getCampaignStats' : IDL.Func([], [CampaignStats], ['query']),
    'getMealsSponsored' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalAmountRaised' : IDL.Func([], [IDL.Nat], ['query']),
    'makeDonation' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };